[package]
name = "pg_query"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "pg_query"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0"

[dependencies.pg_query-sys]
package = "libpg_query-sys"
path = "libpg_query-sys"
version = "0.1"
